### ISSUE TITLE
Getting Started with JupyterHub - Architecture Tutorial

### ISSUE THREAD

**Issue by willingc** [minrk/jupyterhub-pydata-2016#1]
A few thoughts after watching the video. I would initially move over everything but the keynote file (because open source and the html font rendering is wonky) and change the README to correspond.

I'm (partially for my own benefit) putting together an additional notebook with a timeline of your talk with youtube clips that are clickable as well as Markdown to coordinate concepts and links to our JupyterHub documentation. The notebook could be a self guided tour through the talk, slides, and concepts. A more polished version than what I played around with for [CPython internals](https://github.com/willingc/pyladies-cpython) training last year. Or a lower tech version of O'Reilly's Oriole.

Here's a very rough outline of the timeline that I started piecing together this morning:

```
JupyterHub Tutorial timeline

YouTube https://youtu.be/LkgSCjyv75s

0:00 Welcome and Intro

0:01:00 GitHub repo that accompanies the talk

0:01:44 What is the Notebook?

0:03:00 What is a Notebook Server?

0:04:17 JupyterHub

0:05:41 Login

0:05:55 Spawner

0:06:27 Proxy

0:07:11 Redirect user

0:07:17 Browser to ask hub for auth

0:07:56 Installation (as admin)

0:10:44 Installation (this repo)

0:11:18 Installation: Caveats

0:12:18 conda-forge - community maintained conda packages
... TBD ...

1:11:00 Q & A

1:13:00 Simula deployment with persistence in Hub
```

If you would like, I could work on the notebook the next few days while I'm travelling and push it to my fork of this repo.

**Comment by minrk** [comment]
Closed by #2
